#!/usr/bin/env python
# vi:set ai sm nu ts=4 sw=4 expandtab:
#
# LUMOS TEXT TEST RUNNER
# $Header: /tmp/cvsroot/lumos/Test/texttestrunner,v 1.3 2008-12-31 00:13:32 steve Exp $
#
# Lumos Light Orchestration System
# Copyright (c) 2005, 2006, 2007, 2008 by Steven L. Willoughby, Aloha,
# Oregon, USA.  All Rights Reserved.  Licensed under the Open Software
# License version 3.0.
#
# This product is provided for educational, experimental or personal
# interest use, in accordance with the terms and conditions of the
# aforementioned license agreement, ON AN "AS IS" BASIS AND WITHOUT
# WARRANTY, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION,
# THE WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A
# PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY OF THE ORIGINAL
# WORK IS WITH YOU.  (See the license agreement for full details, 
# including disclaimer of warranty and limitation of liability.)
#
# Under no curcumstances is this product intended to be used where the
# safety of any person, animal, or property depends upon, or is at
# risk of any kind from, the correct operation of this software or
# the hardware devices which it controls.
#
# USE THIS PRODUCT AT YOUR OWN RISK.
# 
# $Log: not supported by cvs2svn $
# Revision 1.1  2008/12/30 22:58:02  steve
# General cleanup and updating before 0.3 alpha release.
#
import sys, unittest
sys.path.append('../lib')
import Test
unittest.TextTestRunner().run(Test.suite())
for w in Test.accumulated_warnings():
    print "SKIPPED {0} TEST{1}: {2}".format(
        w.count, '' if w.count==1 else 'S',
        w.msg
    )
#
# $Log: not supported by cvs2svn $
#
