#!/usr/bin/perl
# vim:set syntax=perl:
use File::Basename;

$BASE_DIR = shift;
$PDF_DIR = shift;
while ($search_dir = shift) {
	push(@{$MAN_FILES{$search_dir}}, glob("$search_dir/*.[12345678].in"));
}

foreach $dir (sort(keys(%MAN_FILES))) {
	foreach $file (@{$MAN_FILES{$dir}}) {
		$PDF_LIST .= " $PDF_DIR/" . (fileparse($file, qr/\.\d\.in/))[0] . '.pdf';
	}
}

while (<STDIN>) {
	if (/\@\@PDF_BUILD_RULES\@\@/) {
		foreach $dir (sort(keys(%MAN_FILES))) {
			print "\n#Manpages found in $dir:\n";
			foreach $file (@{$MAN_FILES{$dir}}) {
				$mansrc = $file;
				($mandst = $mansrc) =~ s/\.in$//;
				if ($mansrc eq $mandst) {
					die("Can't deal with manpage file $file!\n");
				}
				print "$PDF_DIR/", (fileparse($file, qr/\.\d\.in/))[0], '.pdf: ', $mandst, "\n";
				print "\tgroff -man $mandst | ps2pdf -sPaperSize=Letter - \$\@\n";
				print "\n";
				print "$mandst: $mansrc\n";
				print "\t$BASE_DIR/update_manpage < $mansrc > \$\@\n";
			}
		}
		next;
	}
	s/\@\@PDF_LIST\@\@/$PDF_LIST/g;
	print;
}
